name: Java Build Test

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '21'
      
      - name: Build Java Program
        run: |
          javac -cp "./lib/gson-2.2.2.jar" ./src/**/*.java

      - name: Verify Build Success
        run: |
          ls ./bin/Main.class  # Check if target directory exists (indicates successful build)
